/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\studyspace\\vuepressOriginCode\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7e27aa86",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e27aa86").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4457cd9e",
    path: "/guide/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4457cd9e").then(next)
    },
  },
  {
    name: "v-3032cfd1",
    path: "/guide/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3032cfd1").then(next)
    },
  },
  {
    name: "v-3db7e194",
    path: "/guide/clis/DGT-cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3db7e194").then(next)
    },
  },
  {
    name: "v-372ded8e",
    path: "/guide/info/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-372ded8e").then(next)
    },
  },
  {
    name: "v-84fce784",
    path: "/guide/info/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84fce784").then(next)
    },
  },
  {
    name: "v-60757dbe",
    path: "/guide/d-ui/directives.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60757dbe").then(next)
    },
  },
  {
    name: "v-9c9d5674",
    path: "/guide/clis/npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c9d5674").then(next)
    },
  },
  {
    name: "v-482873c4",
    path: "/guide/performanceOptimization/network.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-482873c4").then(next)
    },
  },
  {
    name: "v-93e21280",
    path: "/guide/info/resumeNew.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93e21280").then(next)
    },
  },
  {
    name: "v-c59f7a78",
    path: "/guide/utils/sdk.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c59f7a78").then(next)
    },
  },
  {
    name: "v-f7f455b8",
    path: "/guide/utils/utils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7f455b8").then(next)
    },
  },
  {
    name: "v-66205537",
    path: "/guide/webpack/loaders/cacheloader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66205537").then(next)
    },
  },
  {
    name: "v-33be977d",
    path: "/guide/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33be977d").then(next)
    },
  },
  {
    path: "/guide/utils/index.html",
    redirect: "/guide/utils/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]