/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DGT WORKSPACE",
  "description": "used to record the knowledge of front-end development",
  "base": "/studyspace/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {
        "sidebarDepth": 1
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b2589aac",
      "path": "/",
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "title": "积累的工具",
      "frontmatter": {
        "sidebarDepth": "1,",
        "sidebar": "auto"
      },
      "regularPath": "/guide/utils/utils.html",
      "relativePath": "guide/utils/utils.md",
      "key": "v-e4588252",
      "path": "/guide/utils/utils.html",
      "headers": [
        {
          "level": 2,
          "title": "积累的工具",
          "slug": "积累的工具"
        }
      ],
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "title": "Hello 1",
      "frontmatter": {},
      "regularPath": "/guide/1.html",
      "relativePath": "guide/1.md",
      "key": "v-16f39a64",
      "path": "/guide/1.html",
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "title": "Hello 2",
      "frontmatter": {},
      "regularPath": "/guide/2.html",
      "relativePath": "guide/2.md",
      "key": "v-69525104",
      "path": "/guide/2.html",
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "frontmatter": {
        "sidebarDepth": "2,",
        "sidebar": "auto"
      },
      "regularPath": "/guide/info/resume.html",
      "relativePath": "guide/info/resume.md",
      "key": "v-7161141e",
      "path": "/guide/info/resume.html",
      "headers": [
        {
          "level": 2,
          "title": "个人信息",
          "slug": "个人信息"
        },
        {
          "level": 2,
          "title": "技能清单",
          "slug": "技能清单"
        },
        {
          "level": 2,
          "title": "工作经历",
          "slug": "工作经历"
        },
        {
          "level": 3,
          "title": "广州欣纬智慧安全科技有限公司（ 2019年10月 ~ 2022年4月）",
          "slug": "广州欣纬智慧安全科技有限公司-2019年10月-2022年4月"
        },
        {
          "level": 3,
          "title": "深圳涌浪网络科技有限公司 （ 2018年10月 ~ 2019年9月 ）",
          "slug": "深圳涌浪网络科技有限公司-2018年10月-2019年9月"
        },
        {
          "level": 2,
          "title": "个人账号",
          "slug": "个人账号"
        }
      ],
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "个人简历",
        "link": "/guide/info/resume/"
      },
      {
        "text": "Utils工具类",
        "link": "/guide/utils/utils/"
      }
    ],
    "sidebar": {
      "/": [
        {
          "title": "plugins",
          "collapsable": true,
          "children": [
            {
              "title": "去掉全部console",
              "path": "/guide/1.md"
            }
          ]
        }
      ],
      "/guide/utils/utils/": [
        {
          "title": "总结的工具类",
          "collapsable": true,
          "children": [
            {
              "title": "工具类",
              "path": "/guide/utils/utils.md"
            }
          ]
        }
      ]
    }
  }
}