/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DGT WORKSPACE",
  "description": "used to record the knowledge of front-end development",
  "base": "/studyspace/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b2589aac",
      "path": "/",
      "lastUpdated": "4/24/2023, 7:03:01 PM",
      "lastUpdatedTimestamp": 1682334181000
    },
    {
      "title": "Hello 1",
      "frontmatter": {},
      "regularPath": "/guide/1.html",
      "relativePath": "guide/1.md",
      "key": "v-16f39a64",
      "path": "/guide/1.html",
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "title": "Hello 2",
      "frontmatter": {},
      "regularPath": "/guide/2.html",
      "relativePath": "guide/2.md",
      "key": "v-69525104",
      "path": "/guide/2.html",
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/clis/DGT-cli.html",
      "relativePath": "guide/clis/DGT-cli.md",
      "key": "v-0bb22a87",
      "path": "/guide/clis/DGT-cli.html",
      "lastUpdated": "4/24/2023, 7:03:01 PM",
      "lastUpdatedTimestamp": 1682334181000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/info/intro.html",
      "relativePath": "guide/info/intro.md",
      "key": "v-4a7eaffe",
      "path": "/guide/info/intro.html",
      "lastUpdated": "4/24/2023, 7:03:01 PM",
      "lastUpdatedTimestamp": 1682334181000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/clis/npm.html",
      "relativePath": "guide/clis/npm.md",
      "key": "v-7fd140b9",
      "path": "/guide/clis/npm.html",
      "lastUpdated": "4/24/2023, 7:03:01 PM",
      "lastUpdatedTimestamp": 1682334181000
    },
    {
      "frontmatter": {
        "sidebarDepth": "2,",
        "sidebar": "auto"
      },
      "regularPath": "/guide/info/resumeNew.html",
      "relativePath": "guide/info/resumeNew.md",
      "key": "v-09f4e39a",
      "path": "/guide/info/resumeNew.html",
      "headers": [
        {
          "level": 2,
          "title": "个人信息",
          "slug": "个人信息"
        },
        {
          "level": 2,
          "title": "技能清单",
          "slug": "技能清单"
        },
        {
          "level": 2,
          "title": "工作经历",
          "slug": "工作经历"
        },
        {
          "level": 3,
          "title": "中电万维信息技术有限公司（ 2022年5月 ~ 2023年6月）",
          "slug": "中电万维信息技术有限公司-2022年5月-2023年6月"
        },
        {
          "level": 3,
          "title": "广州欣纬智慧安全科技有限公司（ 2019年10月 ~ 2022年4月）",
          "slug": "广州欣纬智慧安全科技有限公司-2019年10月-2022年4月"
        },
        {
          "level": 2,
          "title": "个人账号",
          "slug": "个人账号"
        }
      ]
    },
    {
      "title": "积累的工具",
      "frontmatter": {
        "sidebarDepth": "1,",
        "sidebar": "auto"
      },
      "regularPath": "/guide/utils/utils.html",
      "relativePath": "guide/utils/utils.md",
      "key": "v-e4588252",
      "path": "/guide/utils/utils.html",
      "headers": [
        {
          "level": 2,
          "title": "积累的工具",
          "slug": "积累的工具"
        }
      ],
      "lastUpdated": "4/23/2023, 4:33:55 PM",
      "lastUpdatedTimestamp": 1682238835000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/utils/",
      "relativePath": "guide/utils/index.md",
      "key": "v-8c7f1620",
      "path": "/guide/utils/",
      "lastUpdated": "4/24/2023, 7:03:01 PM",
      "lastUpdatedTimestamp": 1682334181000
    },
    {
      "frontmatter": {
        "sidebarDepth": "2,",
        "sidebar": "auto"
      },
      "regularPath": "/guide/info/resume.html",
      "relativePath": "guide/info/resume.md",
      "key": "v-7161141e",
      "path": "/guide/info/resume.html",
      "headers": [
        {
          "level": 2,
          "title": "个人信息",
          "slug": "个人信息"
        },
        {
          "level": 2,
          "title": "技能清单",
          "slug": "技能清单"
        },
        {
          "level": 2,
          "title": "工作经历",
          "slug": "工作经历"
        },
        {
          "level": 3,
          "title": "中电万维信息技术有限公司（ 2022年5月 ~ 2023年6月）",
          "slug": "中电万维信息技术有限公司-2022年5月-2023年6月"
        },
        {
          "level": 3,
          "title": "广州欣纬智慧安全科技有限公司（ 2019年10月 ~ 2022年4月）",
          "slug": "广州欣纬智慧安全科技有限公司-2019年10月-2022年4月"
        },
        {
          "level": 2,
          "title": "个人账号",
          "slug": "个人账号"
        }
      ],
      "lastUpdated": "5/25/2023, 10:31:09 AM",
      "lastUpdatedTimestamp": 1684981869000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/utils/sdk.html",
      "relativePath": "guide/utils/sdk.md",
      "key": "v-6304fdf7",
      "path": "/guide/utils/sdk.html",
      "lastUpdated": "4/24/2023, 3:37:50 PM",
      "lastUpdatedTimestamp": 1682321870000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/webpack/loaders/cacheloader.html",
      "relativePath": "guide/webpack/loaders/cacheloader.md",
      "key": "v-53e2b2ea",
      "path": "/guide/webpack/loaders/cacheloader.html",
      "lastUpdated": "5/25/2023, 10:31:09 AM",
      "lastUpdatedTimestamp": 1684981869000
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后更新时间",
    "sidebarDepth": 2,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "个人简历v1",
        "link": "/guide/info/resume/"
      },
      {
        "text": "个人简历v2",
        "link": "/guide/info/resumeNew/"
      },
      {
        "text": "Utils工具类",
        "link": "/guide/utils/utils/"
      }
    ],
    "sidebar": {
      "/": [
        {
          "title": "plugins",
          "collapsable": false,
          "children": [
            {
              "title": "前端监控埋点实践",
              "path": "/guide/utils/sdk.md"
            }
          ]
        },
        {
          "title": "脚手架",
          "collapsable": false,
          "children": [
            {
              "title": "一个简易的脚手架",
              "path": "/guide/clis/DGT-cli.md"
            }
          ]
        },
        {
          "title": "npm插件",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            {
              "title": "npm插件开发教程",
              "path": "/guide/clis/npm.md"
            }
          ]
        },
        {
          "title": "webpack",
          "collapsable": true,
          "children": [
            {
              "title": "webpack-loader",
              "collapsable": true,
              "children": [
                {
                  "title": "cacheloader",
                  "path": "/guide/webpack/loaders/cacheloader.md"
                }
              ]
            },
            {
              "title": "webpack-plugin",
              "path": "/guide/clis/npm.md"
            }
          ]
        }
      ],
      "/guide/utils/utils/": [
        {
          "title": "总结的工具类",
          "collapsable": true,
          "children": [
            {
              "title": "工具类",
              "path": "/guide/utils/utils.md"
            }
          ]
        }
      ]
    }
  }
}