/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DGT WORKSPACE",
  "description": "used to record the knowledge of front-end development",
  "base": "/studyspace/",
  "headTags": [],
  "pages": [
    {
      "title": "Hello 1",
      "frontmatter": {},
      "regularPath": "/guide/1.html",
      "relativePath": "guide/1.md",
      "key": "v-16f39a64",
      "path": "/guide/1.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b2589aac",
      "path": "/"
    },
    {
      "title": "Hello 2",
      "frontmatter": {},
      "regularPath": "/guide/2.html",
      "relativePath": "guide/2.md",
      "key": "v-69525104",
      "path": "/guide/2.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/info/resume.html",
      "relativePath": "guide/info/resume.md",
      "key": "v-7161141e",
      "path": "/guide/info/resume.html",
      "headers": [
        {
          "level": 2,
          "title": "个人信息",
          "slug": "个人信息"
        },
        {
          "level": 2,
          "title": "技能清单",
          "slug": "技能清单"
        },
        {
          "level": 2,
          "title": "工作经历",
          "slug": "工作经历"
        },
        {
          "level": 3,
          "title": "广州欣纬智慧安全科技有限公司（ 2019年10月 ~ 2022年4月）",
          "slug": "广州欣纬智慧安全科技有限公司-2019年10月-2022年4月"
        },
        {
          "level": 3,
          "title": "深圳涌浪网络科技有限公司 （ 2018年10月 ~ 2019年9月 ）",
          "slug": "深圳涌浪网络科技有限公司-2018年10月-2019年9月"
        },
        {
          "level": 2,
          "title": "个人账号",
          "slug": "个人账号"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "简介",
        "collapsable": false,
        "children": [
          {
            "title": "resume",
            "path": "/guide/info/resume.md"
          }
        ]
      },
      {
        "title": "plugins",
        "collapsable": false,
        "children": [
          {
            "title": "去掉全部console测试",
            "path": "/guide/1.md"
          }
        ]
      },
      {
        "title": "loaders",
        "collapsable": false,
        "children": [
          {
            "title": "生成打包信息",
            "path": "/guide/2.md"
          }
        ]
      }
    ]
  }
}